FROM golang:1.21

WORKDIR /app

# Install specific version of air that's compatible with Go 1.21
RUN go install github.com/cosmtrek/air@v1.49.0

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application
COPY . .

# Command to run air
CMD ["air", "-c", ".air.toml"] 